moved to zsh

diff --git a/extensions/prompt b/extensions/prompt
--- a/extensions/prompt
+++ b/extensions/prompt
@@ -1,24 +1,42 @@
-function gb {
-  branch=$(git symbolic-ref HEAD 2> /dev/null || false)
-  branch=${branch##*/}
-  if [[ $branch ]]; then echo " [$branch]"; fi
-}
+# Ideas:
+#  - full line prompt?
+#  - hostname, colored using hash of hostname
+#  - compressed ts
 
-function rv {
-  rv=$?
-  if [ $rv -ne 0 ]; then echo "($rv) "; fi
-}
+if [ -n "$ZSH_VERSION" ]; then
+    # assume Zsh
+    # TODO: 
+    # - add return value if last command failed ('rv')
+    # - add add git branch if we are in a directory with git ('gb')
 
-function dashes {
-  s=`printf "%*s" $COLUMNS`; 
-  echo "${s// /-}"
-}
-
-PS1='`rv`${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]`gb`\n\$ '
-
-#touch ~
-#PS1="`dashes`\n`rv`${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]`gb`\n\$ "
-
-# full line?
-# hostname, colored using hash of hostname
-# compressed ts
+    # From: https://github.com/robbyrussell/oh-my-zsh/pull/409/files
+    function prompt_char {
+      if [ $UID -eq 0 ]; then echo "#"; else echo $; fi
+    }
+    autoload -U colors && colors
+    PROMPT="%{$fg[green]%}%n@%m%{$fg[white]%}:%{$fg[blue]%}%~%{$fg[white]%}
+$(prompt_char)%{$reset_color%} "
+elif [ -n "$BASH_VERSION" ]; then
+    # assume Bash
+    function gb {
+      branch=$(git symbolic-ref HEAD 2> /dev/null || false)
+      branch=${branch##*/}
+      if [ ! -z $branch ]; then echo " [$branch]"; fi
+    }
+    
+    function rv {
+      rv=$?
+      if [ $rv -ne 0 ]; then echo "($rv) "; fi
+    }
+    
+    function dashes {
+      s=`printf "%*s" $COLUMNS`; 
+      echo "${s// /-}"
+    }
+    
+    PS1='`rv`${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]`gb`\n\$ '
+    #PS1="`dashes`\n`rv`${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]`gb`\n\$ "
+else
+    # asume something else
+    :
+fi
